Repository LMMS/lmms, pull requests merged in 2019-11, with the labels that each got.

#4884 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: bot-skip

#5272 Fix #3983 w/ @zonkmachine
  src/core/FxMixer.cpp
Labels: needs code review, needs testing

#5300 Fix remote plugin crash reading parameters from Grooove plugin
  plugins/vst_base/RemoteVstPlugin.cpp
Labels: needs testing
