Repository LMMS/lmms, pull requests merged in 2019-05, with the labels that each got.

#4959 Show/Focus BBEditor on TrackLabelButton click #4946
  src/tracks/BBTrack.cpp
Labels: gui

#4960 fix hanging mouse in piano roll (#4822)
  src/gui/TimeLineWidget.cpp
  src/gui/editors/AutomationEditor.cpp
  src/gui/editors/PianoRoll.cpp
Labels: needs code review

#4966 Fix race condition in NotePlayHandleManager
  src/core/NotePlayHandle.cpp
Labels: core
