Repository LMMS/lmms, pull requests merged in 2019-10, with the labels that each got.

#5133 Add close button to SideBarWidget
  include/SideBarWidget.h
  src/gui/widgets/SideBar.cpp
  src/gui/widgets/SideBarWidget.cpp
Labels: needs code review, needs testing

#5003 Rubberband fix for selecting large area in Songeditor
  include/SongEditor.h
  include/Track.h
  include/TrackContainerView.h
  src/gui/TrackContainerView.cpp
  src/gui/editors/SongEditor.cpp
  src/gui/widgets/Rubberband.cpp
Labels: needs testing

#5237 Show icon on 'Turn off all notes' button
  plugins/vestige/vestige.cpp
Labels: bug, gui

#4705 Allow mid-note automation of BitInvader sample length
  plugins/bit_invader/bit_invader.cpp
  plugins/bit_invader/bit_invader.h
Labels: in progress

#5245 CircleCI: Suport macOS
  .circleci/config.yml
Labels: CI
