Repository LMMS/lmms, pull requests merged in 2019-09, with the labels that each got.

#3820 Rewrite the setup dialog
  include/ConfigManager.h
  include/SetupDialog.h
  plugins/MidiImport/MidiImport.cpp
  plugins/sf2_player/sf2_player.cpp
  src/core/ConfigManager.cpp
  src/core/audio/AudioJack.cpp
  src/core/audio/AudioOss.cpp
  src/core/audio/AudioPortAudio.cpp
  src/core/audio/AudioPulseAudio.cpp
  src/core/audio/AudioSdl.cpp
  src/core/audio/AudioSndio.cpp
  src/core/audio/AudioSoundIo.cpp
  src/gui/AudioDeviceSetupWidget.cpp
  src/gui/GuiApplication.cpp
  src/gui/MainWindow.cpp
  src/gui/MidiSetupWidget.cpp
  src/gui/SetupDialog.cpp
Labels: enhancement, gui

#5071 Fixes #4984 - Remove maximize from Meter (Metro) menu
  src/gui/widgets/TempoSyncKnob.cpp
Labels: needs testing

#5127 Fix stuck keys when dragging on piano view
  src/core/NotePlayHandle.cpp
Labels: needs testing

#5146 Add save/load of PianoRoll marked semitones
  include/PianoRoll.h
  src/gui/editors/PianoRoll.cpp
Labels: needs testing

#5137 Fix #4188 - Check for failed std::find
  src/gui/editors/PianoRoll.cpp
Labels: needs testing

#4768 Export - Issues with file name/suffix
  src/core/Song.cpp
Labels: in progress
