Repository LMMS/lmms, pull requests merged in 2019-07, with the labels that each got.

#4973 Enhanced snapping in song editor
  data/themes/classic/proportional_snap.png
  data/themes/default/proportional_snap.png
  include/MidiTime.h
  include/SongEditor.h
  include/Track.h
  src/core/Track.cpp
  src/core/midi/MidiTime.cpp
  src/gui/TimeLineWidget.cpp
  src/gui/editors/SongEditor.cpp
  src/tracks/SampleTrack.cpp
Labels: needs testing

#4034 Use mean based logic for controlling loop points.
  src/gui/TimeLineWidget.cpp
Labels: enhancement, ux

#4711 Better French translations in the menu item file
  cmake/linux/lmms.desktop
Labels: enhancement, needs clarification
