Repository LMMS/lmms, pull requests merged in 2020-05, with the labels that each got.

#5477 Sample track activity indicator
  include/FadeButton.h
  include/InstrumentTrack.h
  include/SampleTrack.h
  include/Track.h
  src/core/Track.cpp
  src/gui/widgets/FadeButton.cpp
  src/tracks/InstrumentTrack.cpp
  src/tracks/SampleTrack.cpp
Labels: enhancement

#5441 VST preset preview
  include/InstrumentTrack.h
  plugins/vestige/vestige.cpp
  src/core/PresetPreviewPlayHandle.cpp
  src/tracks/InstrumentTrack.cpp
Labels: needs code review, needs style review, needs testing

#5321 Show vst parameter string
  include/CustomTextKnob.h
  include/Knob.h
  include/aeffectx.h
  plugins/VstEffect/VstEffectControls.cpp
  plugins/VstEffect/VstEffectControls.h
  plugins/vestige/vestige.cpp
  plugins/vestige/vestige.h
  plugins/vst_base/RemoteVstPlugin.cpp
  plugins/vst_base/VstPlugin.cpp
  plugins/vst_base/VstPlugin.h
  plugins/vst_base/communication.h
  src/gui/CMakeLists.txt
  src/gui/widgets/CustomTextKnob.cpp
Labels: needs testing

#4574 Divide knob step size by 1000 for LADSPA effects, and minor changes to scroll wheel behavior
  src/core/LadspaControl.cpp
  src/gui/widgets/Knob.cpp
Labels: needs code review

#5341 Implement compress action for commandline use
  doc/bash-completion/lmms
  src/core/main.cpp
Labels: needs style review

#5487 Fix #5483: sf2_player: No crash when file is no soundfont
  plugins/sf2_player/sf2_player.cpp
Labels: needs code review, needs style review

#5489 Fix #4201: BB editor: adjust cursor position
  data/themes/classic/style.css
  data/themes/default/style.css
  include/Track.h
  src/core/Track.cpp
Labels: needs code review, needs style review

#5515 Compensate beat note length when stretching
  src/gui/editors/PianoRoll.cpp
Labels: bug
