Repository LMMS/lmms, pull requests merged in 2020-09, with the labels that each got.

#5536 basics: Change sampleFrame to use `std::array`
  include/LocklessRingBuffer.h
  include/lmms_basics.h
  plugins/Delay/StereoDelay.cpp
  plugins/Delay/StereoDelay.h
  src/core/Effect.cpp
  src/core/SampleBuffer.cpp
  src/core/audio/AudioDevice.cpp
Labels: core

#5621 Don't give clips a hidden default name (Fix #5528)
  include/DataFile.h
  include/ProjectVersion.h
  src/core/DataFile.cpp
  src/core/Track.cpp
  src/tracks/BBTrack.cpp
  src/tracks/InstrumentTrack.cpp
  src/tracks/Pattern.cpp
Labels: needs code review

#5196 Add auto-highlight scale and key selection
  include/PianoRoll.h
  src/gui/editors/PianoRoll.cpp
Labels: needs code review, needs testing
