Repository LMMS/lmms, pull requests merged in 2025-03, with the labels that each got.

#7700 FileBrowser: "Open containing folder" automatically selects file in the OS's file manager
  include/FileBrowser.h
  include/FileRevealer.h
  src/gui/CMakeLists.txt
  src/gui/FileBrowser.cpp
  src/gui/FileRevealer.cpp
Labels: enhancement, gui

#7770 Upgrade Amplifier plugin PNG assets to SVG
  plugins/Amplifier/AmplifierControlDialog.cpp
  plugins/Amplifier/CMakeLists.txt
  plugins/Amplifier/artwork.png
  plugins/Amplifier/artwork.svg
  plugins/Amplifier/logo.png
  plugins/Amplifier/logo.svg
Labels: enhancement, gui

#7771 Upgrade Bass Booster plugin PNG assets to SVG
  plugins/BassBooster/CMakeLists.txt
  plugins/BassBooster/artwork.png
  plugins/BassBooster/artwork.svg
  plugins/BassBooster/logo.png
  plugins/BassBooster/logo.svg
Labels: enhancement, gui

#7777 Upgrade ReverbSC plugin PNG assets to SVG
  plugins/ReverbSC/CMakeLists.txt
  plugins/ReverbSC/artwork.png
  plugins/ReverbSC/artwork.svg
  plugins/ReverbSC/logo.png
  plugins/ReverbSC/logo.svg
Labels: enhancement, gui

#7775 Upgrade Flanger plugin PNG assets to SVG
  plugins/Flanger/CMakeLists.txt
  plugins/Flanger/artwork.png
  plugins/Flanger/artwork.svg
  plugins/Flanger/logo.png
  plugins/Flanger/logo.svg
Labels: enhancement, gui

#7776 Upgrade Peak Controller plugin PNG assets to SVG
  plugins/PeakControllerEffect/CMakeLists.txt
  plugins/PeakControllerEffect/artwork.png
  plugins/PeakControllerEffect/artwork.svg
  plugins/PeakControllerEffect/logo.png
  plugins/PeakControllerEffect/logo.svg
Labels: enhancement, gui

#7772 Upgrade Bitcrusher plugin PNG assets to SVG
  plugins/Bitcrush/CMakeLists.txt
  plugins/Bitcrush/artwork.png
  plugins/Bitcrush/artwork.svg
  plugins/Bitcrush/logo.png
  plugins/Bitcrush/logo.svg
Labels: enhancement, gui

#7774 Upgrade Dual Filter plugin PNG assets to SVG
  plugins/DualFilter/CMakeLists.txt
  plugins/DualFilter/artwork.png
  plugins/DualFilter/artwork.svg
  plugins/DualFilter/logo.png
  plugins/DualFilter/logo.svg
Labels: enhancement, gui

#7781 Rework Crossover EQ plugin GUI
  data/themes/default/fader_knob.png
  data/themes/default/fader_knob.svg
  include/Fader.h
  include/embed.h
  plugins/CrossoverEQ/CMakeLists.txt
  plugins/CrossoverEQ/CrossoverEQControlDialog.cpp
  plugins/CrossoverEQ/CrossoverEQControls.cpp
  plugins/CrossoverEQ/artwork.png
  plugins/CrossoverEQ/artwork.svg
  plugins/CrossoverEQ/fader_knob2.png
  plugins/CrossoverEQ/logo.png
  plugins/CrossoverEQ/logo.svg
  src/gui/widgets/Fader.cpp
  src/gui/widgets/PixmapButton.cpp
Labels: enhancement, gui

#7795 Fix track name not updating
  src/gui/MixerView.cpp
Labels: bug, gui, master branch

#7804 Enable CMAKE_EXPORT_COMPILE_COMMANDS
  CMakeLists.txt
Labels: enhancement, cmake

#7719 Add ability to change sample rate in the settings menu
  include/AudioEngine.h
  include/SetupDialog.h
  src/core/AudioEngine.cpp
  src/gui/modals/ExportProjectDialog.cpp
  src/gui/modals/SetupDialog.cpp
  src/gui/modals/export_project.ui
Labels: needs code review, needs testing

#7779 Fix track operations button alignment, size, and style
  data/themes/classic/style.css
  data/themes/default/gear.svg
  data/themes/default/headphones.svg
  data/themes/default/mute_active.svg
  data/themes/default/mute_inactive.svg
  data/themes/default/solo_active.svg
  data/themes/default/solo_inactive.svg
  data/themes/default/speaker.svg
  data/themes/default/speaker_slash.svg
  data/themes/default/style.css
  data/themes/default/trackop.png
  include/InstrumentTrackWindow.h
  include/MixerChannelView.h
  include/SampleTrackWindow.h
  include/TrackOperationsWidget.h
  plugins/CrossoverEQ/CrossoverEQControlDialog.cpp
  src/gui/MixerChannelView.cpp
  src/gui/SampleTrackWindow.cpp
  src/gui/instrument/InstrumentTrackWindow.cpp
  src/gui/tracks/TrackOperationsWidget.cpp
Labels: enhancement, gui, needs code review, needs testing

#7780 Add build flags to output of lmms --version
  src/CMakeLists.txt
  src/core/main.cpp
  src/lmmsversion.h.in
Labels: enhancement
