Repository LMMS/lmms, pull requests merged in 2025-02, with the labels that each got.

#7558 Use templates for common geometric constants
  include/BasicFilters.h
  include/DspEffectLibrary.h
  include/MidiEvent.h
  include/Oscillator.h
  include/QuadratureLfo.h
  include/interpolation.h
  include/lmms_constants.h
  include/lmms_math.h
  include/panning.h
  include/panning_constants.h
  plugins/Compressor/Compressor.cpp
  plugins/Delay/Lfo.cpp
  plugins/Delay/Lfo.h
  plugins/Dispersion/Dispersion.cpp
  plugins/Eq/EqCurve.cpp
  plugins/Eq/EqFilter.h
  plugins/Eq/EqSpectrumView.cpp
  plugins/Flanger/FlangerEffect.cpp
  plugins/GranularPitchShifter/GranularPitchShifterEffect.cpp
  plugins/GranularPitchShifter/GranularPitchShifterEffect.h
  plugins/MultitapEcho/MultitapEcho.h
  plugins/Xpressive/ExprSynth.cpp
  plugins/Xpressive/Xpressive.cpp
  src/core/BandLimitedWave.cpp
  src/core/Instrument.cpp
  src/core/Oscillator.cpp
  src/core/fft_helpers.cpp
  src/gui/editors/AutomationEditor.cpp
  src/gui/editors/PianoRoll.cpp
  src/gui/widgets/FloatModelEditorBase.cpp
  src/gui/widgets/GroupBox.cpp
  src/gui/widgets/Knob.cpp
  src/tracks/SampleTrack.cpp
Labels: needs testing

#6331 Reload stylesheet when CSS file changes
  include/LmmsStyle.h
  src/gui/LmmsStyle.cpp
Labels: enhancement

#7687 Add VST64 targets for Linux ARM64
  .github/workflows/build.yml
  cmake/modules/CheckWineGcc.cmake
  cmake/modules/FindWine.cmake
  plugins/VstBase/RemoteVstPlugin64.cmake
Labels: enhancement, compatibility, vst

#7694 VersionInfo: Mimic github's hash styling
  cmake/modules/VersionInfo.cmake
Labels: enhancement

#7691 Allow plugins to be skipped at runtime
  cmake/linux/apprun-hooks/carla-hook.sh
  include/PluginFactory.h
  src/core/PluginFactory.cpp
Labels: enhancement

#7704 Add Wayland support to the AppImage
  .github/workflows/deps-ubuntu-24.04-gcc.txt
  cmake/linux/LinuxDeploy.cmake
  cmake/linux/apprun-hooks/wayland-hook.sh
Labels: enhancement
